name: CommandCharger
main: xXSirGamesXx\CommandCharger\Main
api: 3.0.0-ALPHA7
version: 1.0.0-INDEV
description: "Charge Players money for using specific commands"

commands:
  commandcharge:
    description: "example command description"
    permission: cc.cmd
    aliases: ["cc"]

permissions:
  cc.cmd:
    default: op
    description: "Example permission description"
