name: ExamplePlugin
main: PocketEssential\ExamplePlugin\ExamplePlugin
api:
- 2.0.0
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7
version: 1.0.0
description: "Charge Players money for using specific commands"

commands:
  commandcharge:
    description: "example command description"
    permission: example.permission
    aliases: ["cc"]

permissions:
  cc.use:
    default: true
    description: "Example permission description"
