name: CommandCharger
main: xXSirGamesXx\CommandCharger\Main
api: 3.0.0-ALPHA7
version: 1.1.0-INDEV
author: xxsirbutterxx
description: "Charge Players money for using specific commands"
depend: ["EconomyAPI"]

commands:
  commandcharger:
    description: "example command description"
    permission: cc.cmd
    aliases: ["cc"]

permissions:
  cc.charge.avoid:
    default: op
    description: "Example permission description"
  cc.cmd:
    default: op
    description: "Example permission description"
